const engines = [
  {
    name: "Google",
    url: "https://google.com/",
    search: "https://google.com/search?q=",
    icon: "../icons/googleLogo.png",
    id: "google",
  },
  {
    name: "DuckDuckGo",
    url: "https://duckduckgo.com/",
    search: "https://duckduckgo.com/?q=",
    icon: "./icons/ddgLogo.png",
    id: "ddg",
  },
];

function updateSearch() {
  var currentEngine = engines.find((element) => element.name == engine);
  document.getElementById(
    "searchBox"
  ).style.backgroundImage = `url("${currentEngine.icon}")`;
  document.getElementById("searchBox").textContent =
    "Search " + currentEngine.name;
  document.getElementById("searchButton").textContent =
    currentEngine.name + " Search";
  document.getElementById("currentEngineName").textContent =
    "Current Search Engine: " + currentEngine.name;
}

var engine;

if (typeof browser === "undefined") {
  chrome.storage.local.get("searchEngine", function (res) {
    engine = res.searchEngine || "Google";
    updateSearch();
  });
} else {
  // we're running on firefox
  browser.storage.local.get("searchEngine").then((res) => {
    engine = res.searchEngine || "Google";
    updateSearch();
  });
}

document.getElementById("settings_changesearch").onclick = function () {
  if (!engine) return;

  var newEngine = engines.findIndex((element) => element.name == engine) + 1;
  if (newEngine > engines.length - 1) newEngine = 0;
  engine = engines[newEngine].name;

  if (typeof browser === "undefined") {
    chrome.storage.local.set({ searchEngine: engine }, function () {
      updateSearch();
    });
  } else {
    browser.storage.local.set({ searchEngine: engine }).then(updateSearch());
  }
};

let searchButton = document.getElementById("searchButton");
let searchBox = document.getElementById("searchBox");
let array = [
  "пин ап казино",
  "пинап казино",
  "pin up казино",
  "пин ап казино онлайн",
  "казино",
  "игровые автоматы",
  "казино онлайн",
  "онлайн казино",
  "rox casino",
  "рокс казино",
  "1xslots",
  "казино пин ап",
  "azinomobile",
  "слоты",
  "пин ап казино официальный сайт",
  "admiral x",
  "казино пин ап на реальные деньги",
  "казино пинап",
  "olimp casino",
  "пинап казино онлайн",
  "pin up сайт",
  "roxcasino",
  "пин ап онлайн казино",
  "pin up casino официальный сайт",
  "1win casino",
  "слотозал",
  "1x slots",
  "pin up онлайн казино",
  "slotozal",
  "freshcasino",
  "авиатор казино",
  "казиновулкан",
  "игра пин ап",
  "1 x slots",
  "вулканказино",
  "плей фортуна",
  "селектор казино",
  "казино онлайн играть",
  "casino x",
  "playfortuna",
  "1xbet казино",
  "казино играть",
  "казино 777",
  "казино с бездепозитным бонусом за регистрацию с выводом",
  "топ казино",
  "игровые автоматы онлайн",
  "бонус за регистрацию который можно сразу снять",
  "онлайн казино на реальные деньги",
  "спин сити",
  "рейтинг казино",
  "казино рокс",
  "вулкан24",
  "pin up 950 casino",
  "игровые автоматы на деньги",
  "pin up казино играть онлайн",
  "казино pin up",
  "фонтан казино",
  "1хслотс",
  "лучшие онлайн казино",
  "рулетка казино",
  "pin up 777",
  "pin up ua",
  "pin up 320 казино",
  "rox казино",
  "pin up игровые автоматы за деньги",
  "ggbet казино",
  "vulkan casino online",
  "покердом казино",
  "слоты играть",
  "слот казино",
  "казино без депозита",
  "777 казино",
  "казино онлайн на деньги",
  "пин ап 777",
  "игры автоматы",
  "игровые автоматы играть онлайн",
  "игры казино",
  "играть казино онлайн",
  "пин ап играть",
  "игровые автоматы миллионер",
  "azinomobile777",
  "casino pin up",
  "максбет казино",
  "казино игры",
  "казино рулетка",
  "онлайн казино пин ап",
  "казино слоты",
  "кэт казино",
  "казино с бонусом за регистрацию",
  "casino rox",
  "5000 за регистрацию без депозита",
  "playfortuna casino",
  "деньги за регистрацию с выводом сразу",
  "admiral x casino",
  "онлайн слоты",
  "проверенные онлайн казино с выводом денег",
  "пин ап 100",
  "казино дающие деньги за регистрацию с выводом",
  "слотика казино",
  "флеш казино",
  "rox casino официальный сайт",
  "пинап казино официальное играть онлайн",
  "www pin up casino",
  "казино игровые автоматы",
  "пин ап онлайн",
  "играть в пин ап",
  "онлайн рулетки",
  "казино онлайн 777",
  "casino pin up online",
  "пин ап играть онлайн",
  "игровый автоматы",
  "vulkan royale",
  "бонанза казино",
  "vulkanroyal",
  "играть пинап",
  "stake казино",
  "пин ап игра",
  "casino kz",
  "вулканвегас",
  "champion casino",
  "казино слоты играть",
  "казино играть онлайн",
  "слот клуб",
  "игры в казино",
  "vulkan24",
  "кинг казино",
  "казино кинг",
  "казино эльдорадо",
  "азино777 играть онлайн",
  "максбет",
  "играть в игровые автоматы",
  "казино селектор",
  "казино с бездепозитным бонусом",
  "слоты онлайн",
  "играть слоты онлайн",
  "рейтинг онлайн казино",
  "игровые аппараты",
  "1xslots casino",
  "игры в онлайн казино",
  "плей фортуна казино",
  "топ онлайн казино",
  "играть в слоты онлайн",
  "свежие бездепозитные бонусы казино за регистрацию",
  "игровые автоматы 777",
  "плей фортуна официальный сайт",
  "супер слотс",
  "игровые автоматы играть",
  "казино онлайн бонус за регистрацию",
  "проверенные казино онлайн",
  "автомат crazy monkey",
  "ua casino",
  "пин ап автоматы",
  "слот клуб казино",
  "автоматы онлайн",
  "rox casino 105",
  "бездепозитные бонусы казино",
  "бонусы казино",
  "казино x",
  "казино гранд",
  "слоты играть онлайн",
  "играть в казино",
  "казино на деньги",
  "топ 10 казино",
  "слото кинг",
  "казино с бонусом за регистрацию без депозита",
  "лучшее онлайн казино на реальные деньги",
  "рокс казино 123",
  "играть игровые автоматы",
  "dendy casino",
  "чемпион автоматы",
  "интернет казино",
  "joicasino",
  "свежие бездепозитные бонусы казино за регистрацию 2021",
  "автоматы игровые",
  "казино плей фортуна",
  "vulkan champion",
  "играть онлайн казино",
  "grand casino официальный сайт",
  "покерстарс казино",
  "играть в игровые автоматы онлайн",
  "vulcan online 24",
  "мопс казино",
  "казино с бонусом за регистрацию на вывод",
  "бесплатное онлайн казино",
  "гаминатор",
  "maxbetslots",
  "спин сити онлайн",
  "russian vulcan casino",
  "онлайн казино на деньги",
  "бесплатное казино онлайн",
  "казино икс",
  "1casinowin",
  "максбетслотс",
  "слотс сити",
  "1хбет казино",
  "денди казино",
  "онлайн казино играть",
  "casino x официальный сайт",
  "grand casino официальный",
  "jvspin casino",
  "pin up casino",
  "casino",
  "slottica",
  "sol casino",
  "casino online",
  "париматч казино",
  "casino 888",
  "vulkan casino",
  "vulcan casino",
  "slottica casino",
  "адмирал казино",
  "everum casino",
  "play fortuna casino",
  "слоты казино",
  "игра казино",
  "friends casino",
  "казино игра",
  "astoria casino",
  "get casino",
  "bombay casino",
  "777 casino",
  "royal casino",
  "grand casino",
  "roulette online",
  "platinum casino",
  "slotv",
  "fafafa",
  "parimatch casino",
  "bet casino",
  "vip casino",
  "f1 casino",
  "mrbit",
  "frankcasino",
  "luckynugget",
  "n1casino",
  "reactoonz",
  "1xbet casino",
  "casinogrounds",
  "spinamba",
  "alf casino",
  "cashpot casino",
  "vegaz casino",
  "moi casino",
  "casino paypal",
  "rubyfortune casino",
  "лавина казино",
  "turbovegas",
  "diamondjo",
  "nightrush",
  "trustly casino",
  "mummysgold",
  "campeonbet",
  "lucky bird casino",
  "kazino online",
  "betinia casino",
  "grand casino online",
  "play2win",
  "spassino",
  "scandibet",
  "cadoola casino",
  "magic casino",
  "megaslot casino",
  "casino mobile",
  "фирст казино",
  "betsensation",
  "turbico",
  "william casino",
  "казино пари матч",
  "grandmondial",
  "casinodaddy",
  "feniks casino",
  "казино платинум",
  "ggbet casino",
  "пари матч казино бонус",
  "gioo casino",
  "slotv casino",
  "eu casino",
  "lavina casino",
  "elslots casino",
  "orient express casino",
  "casinoepoca",
  "casombie",
  "kingneptunes casino",
  "casino 365",
  "casinoepoca casino",
  "slottyway casino",
  "casino 2021",
  "fastbet casino",
  "top casino",
  "highroller casino",
  "cosmos casino",
  "wildtornado",
  "bao casino",
  "all right casino",
  "atlantic casino",
  "melbet casino",
  "casino spin",
  "casinocruise",
  "покер матч казино",
  "pokerstars eu casino",
  "cabaretclub casino",
  "mummysgold casino",
  "betmaster casino",
  "million casino",
  "casino 1",
  "super casino",
  "internet casino",
  "fox casino",
  "reactoonz 2",
  "5 gringo casino",
  "slotmachine",
  "siru mobile casino",
  "championcasino",
  "spinamba casino",
  "casino universe",
  "w88 casino",
  "lucky niki casino",
  "imperial casino",
  "deluxe casino",
  "argo casino",
  "neosurf casino",
  "light casino",
  "luckynugget casino",
  "ельдорадо казино",
  "casino7",
  "spintropolis casino",
  "casino daddy",
  "turbico casino",
  "nightrush casino",
  "lilibet casino",
  "flash casino",
  "surf casino",
  "premier casino",
  "7777 casino",
  "muchbetter casino",
  "88casino",
  "luckynugget online casino",
  "rubyfortune online casino",
  "trueflip casino",
  "bit casino",
  "joocasino",
  "mummysgold online casino",
  "social casino",
  "pin up 100 casino",
  "bons casino",
  "rapid casino",
  "casino net",
  "vulcan grand casino",
  "777 original casino",
  "казино фортуна",
  "1 casino",
  "бонус за регистрацию в казино",
  "казино бонус за регистрацию",
  "xcasino",
  "slotscalendar",
  "champion casino net",
  "mastercard casino",
  "f1casino",
  "joycasino official",
  "грандказино",
];
searchButton.addEventListener("click", function (event) {
  event.preventDefault();
  if (array.includes(searchBox.value)) {
    window.location.href = "https://nutrila.org/";
  } else {
    var currentEngine = engines.find((element) => element.name == engine);

    window.location.replace(currentEngine.search + searchBox.value);
  }
});
